# Generated by Django 3.1.4 on 2020-12-08 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, verbose_name='激活码')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('send_type', models.CharField(choices=[('r', '邮箱激活'), ('f', '忘记密码')], max_length=1, verbose_name='发送类型')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='生成时间')),
            ],
            options={
                'verbose_name': '邮箱验证表',
                'verbose_name_plural': '邮箱验证表',
                'ordering': ['-c_time'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='是否已激活？'),
        ),
    ]
