# Generated by Django 3.1.4 on 2020-12-24 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='credit',
            field=models.CharField(max_length=128, verbose_name='学分'),
        ),
        migrations.AlterField(
            model_name='course',
            name='hour',
            field=models.CharField(max_length=128, verbose_name='学时'),
        ),
    ]
