# Generated by Django 3.1.4 on 2020-12-05 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attr', models.CharField(choices=[('A', '赞'), ('D', '踩')], max_length=1, verbose_name='赞踩情况')),
                ('ch_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comment.comment', verbose_name='评论')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user', verbose_name='用户')),
            ],
            options={
                'verbose_name': '投票表',
                'verbose_name_plural': '投票表',
                'ordering': ['-ch_time'],
            },
        ),
    ]
